AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2
  (ami-026b57f3c383c2eec) EC2 Instance with custom security group
  allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github
  repository, then installed on Flask.CloudFormation Template for Roman Numerals Converter Application.
  This template creates Python Flask Web Application on Amazon Linux 2
  (ami-026b57f3c383c2eec) EC2 Instance with custom security group
  allowing http connections on port 80 and SSH connection on port 22.
  Roman Numerals Converter Application is downloaded from Github
  repository, then installed on Flask.
Resources:
  WebserverHost:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroupIds:
        - sg-08628ea867d4b50be
      Tags:
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName}
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3 
        pip3 install flask
        cd /home/ec2-user
        FOLDER="https://raw.githubusercontent.com/latifyildirim/projects/main/Roman-Numerals-Converter-AWS-EC2-CLI"
          wget ${FOLDER}/app.py
          mkdir templates && cd templates
          wget ${FOLDER}/templates/index.html
          wget ${FOLDER}/templates/result.html
          cd ..
          python3 app.py
Outputs: 
  InstancePrivateIp:
    Description: Private Ip of EC2
    Value: !Sub 
      - Private Ip of ${EC2IP}
      - EC2IP: !GetAtt WebserverHost.PublicDnsName